# Generated by Django 4.1.2 on 2022-12-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiendaMusical', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
